# List of valid engines
ENGINES : [ "d8", "wasmtime", "wizard" ]

# Paths to engines and engine-specific options
# Wasmtime
WASMTIME_PATH : "/opt/wasmfx/wasmfxtime/target/release/wasmtime"
WASMTIME_OPTIONS : "run --allow-precompiled -W=exceptions,function-references,gc,stack-switching"

# V8
D8_PATH : "/opt/wasmfx/v8/out/x64.release/d8"
D8_OPTIONS : "--experimental-wasm-wasmfx load.mjs --"

# Wizard
WIZARD_PATH : "/opt/wasmfx/wizard-engine/bin/wizeng.x86-64-linux"
WIZARD_OPTIONS : "--ext:stack-switching --ext:gc --stack-size=65536 --mode=jit"

# List of benchmarks
BENCHMARKS_FIBER_C : [
    "itersum",
    "sieve",
    "state",
    "treesum",
    #"treesumlinear",
    "c10m",
    "pi",
    "skynet",
  ]

# Arguments for benchmarks
ITERSUM_ARGS : 1000000
TREESUM_ARGS : 25
SIEVE_ARGS : 2000

# Wasmtime stack pool sizes for benchmarks that may do better with a different number from the default 1024 stacks
WASMTIME_STACK_POOL_SIZES : {
    "c10m": 10000,
    "sieve": 2000, # this needs to be equal to SIEVE_ARGS
    "skynet" : 6,
}